### ISSUE TITLE
Camera Destroyed Exception

### ISSUE THREAD

**Issue by oOtroyOo** [nyahoon-games/ProjectorForLWRP#3]
``` csharp
internal void RemoveCommandBuffer(CommandBuffer commandBuffer)
{
	m_camera.RemoveCommandBuffer(CameraEvent.BeforeImageEffectsOpaque, commandBuffer);
}
```

Here we need to check camera is notnull

``` csharp
internal void RemoveCommandBuffer(CommandBuffer commandBuffer)
{
	if(m_camera != null) 
 		m_camera.RemoveCommandBuffer(CameraEvent.BeforeImageEffectsOpaque, commandBuffer);
}
```

**Comment by takaokato** [comment]
Thank you for the bug report, but the above code is not a part of ProjectorForLWRP. It must be a code in Dynamic Shadow Projector. I will fix it if m_camera can be null. However, I am wondering if it really happens. When did you observe that m_camera was null? Once m_camera is initialized, it will never be null unless the camera is destroyed. Did you destroy the camera component in the Dynamic Shadow Projector object?

**Comment by oOtroyOo** [comment]
When i'm editting Prefabs.

I realized that the created Camera won't show on inspector. 
 (On the other hand ,I dont know why its hiding ,it should appears. as well ,why Update() is triggered in edit mode)

But the prefab will recognize changes . like this:
![image](https://user-images.githubusercontent.com/19978148/115343616-c8e20780-a1de-11eb-8d47-2dbc8abe8a3a.png)

By apply or revert in several times. the camera has been destroyed .Caused Exception. 
I'm not sure about the exact steps

after all ,it will fix by reactivate the behaviour , not a big problem

**Comment by takaokato** [comment]
Thank you for the explanation. I will fix it by adding camera component if it is missing in a prefab object.

The reason why the camera component is hidden is that there are no properties to be edited by users. However, prefab object does not keep hide flags, and the camera component will be shown after a prefab object is created. I will also fix this problem.

Also, the reason why Update() is triggered is that we need to generate and preview shadows in edit mode, and the components have [ExecuteAlways] attribute.

Anyway, I will close this issue because it is not related to this github repository. Thanks again for your feedback.
